version: "1"
rules:
  - base: master
    upstream: CJCrafter:master # Required. Must be in the same fork network.
    mergeMethod: squash
    reveiwers:
      - OakLoaf
    conflictReviewers: # Optional, on merge conflict assign a reviewer
      - OakLoaf
  - base: dev
    upstream: master # Required. Can be a branch in the same forked repo.
    assignees: # Optional
      - wei
    reviewers: # Optional
      - wei
    conflictReviewers: # Optional, on merge conflict assign a reviewer
      - wei
